### ISSUE TITLE
DICOM SR as naturalized dataset

### ISSUE THREAD

**Issue by NussknackerXXL** [dcmjs-org/dicomweb-client#10]
I need a simple JSON representation of the measurement group data from a DICOM SR object.

I am aware of the dcmjs-library, and its functionality of naturalizing a dataset. Now i was wondering if there are any plans on implementing the function of `DCMJS.data.DicomMetaDictionary.naturalizeDataset()` in this library or would you suggest to just use the dcmjs library for this purpose?

It would be good to get a better JSON representation of the measurement groups and its values then the default response of `retrieveInstanceMetadata`(). For now i am parsing just this response in a format which fits my need like

```
{ "measurementGroupName" : { 
        "measurementName" : "value"
    }, 
    { ... }
} 
```
A question would be, if it is better to use a general dicom parsing method or ajusted to structured report values.

**Comment by swederik** [comment]
Hmm I would retrieve the instance (or its metadata) with this library, and then use dcmjs to naturalize it. I don't think we plan to duplicate that functionality in this library.

**Comment by pieper** [comment]
I agree with @swederik, it's better to keep each library focused on the specific functions and then use the two together when you need both.
