### ISSUE TITLE
multipartDecode is not compatible with Orthanc and retrieveStudy

### ISSUE THREAD

**Issue by vsaase** [dcmjs-org/dicomweb-client#17]
https://github.com/dcmjs-org/dicomweb-client/blob/22bb19a19fc85aa6b34a9399734cd508d15f36ff/src/message.js#L175

Hi,
cutting out the header has to be done for every part.
My setup is Orthanc, which responds to retrieveStudy with a response of the form
```
--7f6c0897-b97c-48ce-8d35-4b749ba0e9f9
Content-Type: application/dicom
Content-Length: 208474
MIME-Version: 1.0

<dicom data 0>
--7f6c0897-b97c-48ce-8d35-4b749ba0e9f9
Content-Type: application/dicom
Content-Length: 208474
MIME-Version: 1.0

<dicom data 1>
--7f6c0897-b97c-48ce-8d35-4b749ba0e9f9--
```
I remember from reading the DICOM standard a while ago that this kind of response is not what you would expect. I think multipartDecode expects at the moment
```
--7f6c0897-b97c-48ce-8d35-4b749ba0e9f9
Content-Type: application/dicom
Content-Length: 208474
MIME-Version: 1.0

<dicom data 0>
--7f6c0897-b97c-48ce-8d35-4b749ba0e9f9
<dicom data 1>
--7f6c0897-b97c-48ce-8d35-4b749ba0e9f9--
```
Here is a pull request that fixes it for me, need to check if it breaks other dicomweb servers
#18

**Comment by pieper** [comment]
Thanks for the report and PR @vsaase 👍 

But since we have been using the client code with dcm4chee and with google's dicomweb, I wonder if this is actually a bug in orthanc.  Would you be able to test and maybe come up with something that works in all?  For example you could test using server.dcmjs.org (which is what backs https://viewer.ohif.org).

**Comment by vsaase** [comment]
Just testet it with dcm4chee, there it's the same problem, the response looks like 
```
--361d3d22-548a-4469-91d7-7f9a5f0bfbea
Content-ID: <0fa11885-879d-4c4a-a314-1215bd3280c1@resteasy-multipart>
Content-Type: application/dicom

<dicom data 0>
--361d3d22-548a-4469-91d7-7f9a5f0bfbea
Content-ID: <c55f9c88-466f-4c0e-9748-2e51cf949052@resteasy-multipart>
Content-Type: application/dicom

<dicom data 1>
--361d3d22-548a-4469-91d7-7f9a5f0bfbea--
```

**Comment by vsaase** [comment]
I think this function should be rewritten such that the boundary is taken from the response header, not from the response data

**Comment by hackermd** [comment]
@pieper I think @vsaase is right. According to [Part 18 Section 8.6.1.2 Multipart Payload](http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_8.6.html#sect_8.6.1.2):

> Each part in a multipart payload shall start with a boundary string, followed by a Content-Type header field.

The template for a part payload looks as follows:

```none
DASH         = "--"
boundary     = 0*69(bchar / SP) bchar
bchar        = DIGIT / ALPHA / "'" / "(" / ")" / "+" / "_"   ; The legal boundary characters
             / "," / "-" / "." / "/" / ":" / "=" / "?"
part         = Content-Type: media-type CRLF
               Content-Location: url CRLF
               (Content-Length: uint CRLF / Content-Encoding: encoding CRLF)
               [Content-Description: text CRLF]
               *(header-field CRLF)
               CRLF
               part-payload
part-payload = *OCTET
```

**Comment by pieper** [comment]
Yes, I believe @vsaase but I wanted to better understand the report - are you saying that this fix will continue to work with dcm4chee/google and will also now work with orthanc?

**Comment by vsaase** [comment]
the fix works at least with dcm4chee and orthanc, didn't test google yet

**Comment by pieper** [comment]
Okay, sounds good then, I went ahead and merged it.  If it works on two servers it should work on google too.
