### ISSUE TITLE
Ascending or descending order?

### ISSUE THREAD

**Issue by thiagosena** [dcmjs-org/dicomweb-client#20]
It's possible to search for studies with ascending or descending order for a specific field in a query?

**Comment by hackermd** [comment]
I don't think this is part of the standard. Part 3.18 Section 7.2 Resources, Representations, and Target URIs states

> In RESTful Web Services, a resource is an abstract object with a type, associated data, relationships to other resources,and a set of methods that operate on it. Resources are grouped into collections. Collections are themselves resources as well. Each collection is unordered and contains only one type of resource. Collections can exist globally, at the top level of an API, but can also be contained inside a resource. In the latter case, we refer to these collections as sub-collections. Sub-collections usually express some kind of "contained in" relationship.
