### ISSUE TITLE
travis build error

### ISSUE THREAD

**Issue by pieper** [dcmjs-org/dicomweb-client#3]
Anyone know where this comes from?

https://travis-ci.com/dcmjs-org/dicomweb-client/builds/84592898?utm_source=email&utm_medium=notification

Maybe this line?
https://github.com/dcmjs-org/dicomweb-client/blob/master/.travis.yml#L12

**Comment by swederik** [comment]
Not sure what the problem was, but it's gone now. Might have been the Node version.
