### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by kerolloz** [dcmjs-org/dicomweb-client#42]

**Comment by juaesto** [comment]
Are there available Typescript definitions?

**Comment by pieper** [comment]
Not that I know of.  If someone feels strongly they could make a PR.

**Comment by hackermd** [comment]
We have [type definitions in Slim](https://github.com/herrmannlab/slim/blob/1263cca1c9776f72a7bcdf474c34e5c873d4b571/types/dicomweb-client/index.d.ts) and it would be nicer to include them in the package distribution.

**Comment by pieper** [comment]
Thank you @hackermd.  Yes, it would make more sense for those to be here along with some tests to ensure they stay up to date if/when the API evolves.

**Comment by hackermd** [comment]
@pieper could you help porting them over from the application into the library?

For the tests, we may need to introduce typescript as a dev dependency.

**Comment by pieper** [comment]
I don't have any particular need for typescript but perhaps @juaesto or @kerolloz would be willing to help out.
