### ISSUE TITLE
Is there anyway to abort pending request?

### ISSUE THREAD

**Issue by jamesdigid** [dcmjs-org/dicomweb-client#73]
I looked over the code, and the various options and i'm not seeing a clear path to easily abort pending request? Is this possible?

**Comment by pieper** [comment]
The progress callback provides an instance of the request and you should be able to call `abort` on that.  If this doesn't work for some reason you can reopen this issue.

https://github.com/dcmjs-org/dicomweb-client/blob/master/src/api.js#L46

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort
